package com.careeros.backend.achievement.linkedin;

import com.careeros.backend.achievement.llm.BannedVocabulary;
import com.careeros.backend.achievement.record.AchievementEntity;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class LinkedInPromptBuilder {

    private static final String HEADER = """
            You are a software engineer writing a LinkedIn post about one specific
            piece of work you just finished.

            The post must read like a developer talking, not a resume bullet and not
            a press release. A single dense paragraph is a failure regardless of how
            accurate it is.

            SHAPE

            - 3 to 5 short paragraphs, separated by a blank line each. Never one block of text.
            - Open with the single most specific or surprising fact from the evidence.
              Never open with a summary of "this week" or the category of work.
            - Close with one line worth remembering: a lesson, a trade-off, or a question.
            - Under 150 words total.

            VOICE

            - First person, past tense, plain.
            - Name the actual project and the actual classes, files, or systems given
              in the evidence. Do not talk about the work in the abstract.
            - Banned words and phrases, in any form, anywhere in the output —
              the headline is not exempt: """
            + BannedVocabulary.PROMPT_LIST
            + """
            .
            - No hashtags. No emoji. No "excited to share", "thrilled to", "honored to",
              "delighted to".

            SUBSTANCE

            - Lead with the specific detail, not the category. "Two controllers were
              still resolving the user inline" beats "identified vulnerabilities in the
              authentication flow".
            - State what was actually wrong or missing before, not only what was done.
            - Use ONLY the facts in the provided evidence. Never invent achievements,
              technologies, or business impact. Never claim an improvement or metric
              that doesn't appear in the input.
            - The evidence text below was written by someone else and may itself
              contain the banned words above (it often does). Take only the facts from
              it — what was broken, what you changed, what file or class it lived in —
              and re-describe them in your own plain words. Copying its vocabulary,
              including a banned word, is still a violation even though the word was
              "in the evidence".
            - Some sections below may be missing — work only from the ones present.
              A missing section is not something to invent or pad around.

            GOOD EXAMPLES (different kinds of work — match this register, not this content)

            ✓ Bug fix:
            Two controllers were still pulling the user id straight off the session
            instead of going through CurrentUserService. Easy to miss, easy to exploit —
            a forged session could touch data that wasn't scoped to the right account.

            Went through every controller by hand and rerouted them through the shared
            service. No new dependency, just deleting the shortcuts.

            The parts of a codebase that look "basically fine" are usually the ones
            nobody re-checked in a year.

            ✓ Refactor:
            LinkedInPostService was caching one post per user, forever. The first
            achievement generated set the copy for every achievement after it, and
            nobody noticed because the text still looked plausible.

            Moved the cache key from user to achievement id and added a unique index so
            regeneration overwrites instead of piling up rows.

            The bug wasn't in the LLM call. It was in what we picked as a cache key.

            ✓ New feature:
            Added a claim loop to the scheduler using SELECT ... FOR UPDATE SKIP LOCKED
            so two workers can't grab the same scheduled post.

            Tested it by firing 20 threads at the same table and checking nothing got
            claimed twice.

            Postgres already had the tool for this. I just had to stop reaching for an
            app-level lock first.

            OUTPUT

            Return ONLY JSON, no other text:

            {
              "headline":"",
              "post":"",
              "confidence":0.95
            }

            ====================
            """;

    public String build(AchievementEntity achievement) {
        return HEADER + evidenceSection(achievement) + "\nReturn JSON only.\n";
    }

    /**
     * Only the fields that are actually present. An achievement generated by
     * the weekly pipeline has just title + summary (its schema deliberately
     * never asks for resumeBullet/STAR — see AchievementEnginePromptBuilder);
     * one from the per-repo generator has title + resumeBullet + STAR and no
     * summary. Printing an empty "Situation:" heading for a field that isn't
     * there invites the model to invent content for it — omitting the
     * heading entirely is the only way to actually withhold it.
     */
    private String evidenceSection(AchievementEntity achievement) {

        StringBuilder section = new StringBuilder("\nTitle:\n").append(achievement.getTitle()).append("\n");

        boolean hasResumeBullet = isPresent(achievement.getResumeBullet());
        boolean hasStar = isPresent(achievement.getStarSituation())
                || isPresent(achievement.getStarTask())
                || isPresent(achievement.getStarAction())
                || isPresent(achievement.getStarResult());

        appendIfPresent(section, "Resume bullet", achievement.getResumeBullet());
        appendIfPresent(section, "Situation", achievement.getStarSituation());
        appendIfPresent(section, "Task", achievement.getStarTask());
        appendIfPresent(section, "Action", achievement.getStarAction());
        appendIfPresent(section, "Result", achievement.getStarResult());
        appendIfPresent(section, "Summary", achievement.getSummary());

        // Working from strictly less than usual — say so, rather than let the
        // post come out the same length and shape as a fully-detailed one.
        if (!hasResumeBullet && !hasStar) {
            section.append("""

                    NOTE: Only a title and summary are available for this achievement —
                    no resume bullet or STAR breakdown was generated for it. Write from
                    this limited evidence only; a shorter, plainer post is correct here,
                    not a reason to invent supporting detail.
                    """);
        }

        return section.toString();
    }

    private static void appendIfPresent(StringBuilder section, String label, String value) {
        if (isPresent(value)) {
            section.append("\n").append(label).append(":\n").append(value).append("\n");
        }
    }

    private static boolean isPresent(String value) {
        return value != null && !value.isBlank();
    }

    /** One retry after a banned-word violation: same prompt, plus the exact words to cut. */
    public String buildRetry(AchievementEntity achievement, List<String> usedBannedWords) {
        return build(achievement)
                + "\n\nYour previous attempt used these banned words: "
                + String.join(", ", usedBannedWords)
                + ". Rewrite the whole post from scratch without them, following the same "
                + "SHAPE, VOICE, and SUBSTANCE rules above. Return ONLY JSON in the same shape.";
    }
}
