spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/careeros
spring.datasource.username=postgres
spring.datasource.password=12345

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# GitHub OAuth
spring.security.oauth2.client.registration.github.client-id=Ov23liZaPI1TQz5DK9cR
spring.security.oauth2.client.registration.github.client-secret=99957bc9e55fe79352b5574d88b88fb5b6cebdad

spring.security.oauth2.client.registration.github.scope=read:user,user:email